[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["cd sales-mgmt && npm ci && npm run build"]

[start]
cmd = "node api/index.js"

[variables]
NODE_ENV = "production"
